#!/bin/bash
#
#Authur: Haggai Lerman
#date: Sept 3 2018
#purpose: Demo of adialog vox that will display a menu
x="5"
MENUBOX=${MENUBOX=dialog}

funcDisplayDialogMenu () { 
 $MENUBOX --title "[ M A I N  M E N U ]" --menu "Use UP/DOWN Arrows to Move and Select or the Number of Your Choice and Enter" 15 45 4 1 "Diplay Haggai Message" 2 "Display Baymax hello" 3 "What next?" X "Exit" 2>choice.txt
}

funcDisplayDialogMenu
case "`cat choice.txt`" in
 1) echo "Follow your dream, work hard and get succssesful";;
 2) echo "Hello World my Baymax Team Jeff, Bibek, Steven, Yumee, Kevin";;
 3) echo "Terraform, ansible, jenkins, google cloud platform etc..";;
 X) break ;;
esac

